### ISSUE TITLE
Notation for using inner classes for JUnit categories with Gradle.

### ISSUE THREAD

**Issue by juddgaddie** [UnquietCode/GradleJUnitCategories#1]

**Comment by juddgaddie** [comment]
https://github.com/UnquietCode/GradleJUnitCategories/blob/master/README.md

**Comment by UnquietCode** [comment]
Yes, I was able to get a resolution for this.
https://discuss.gradle.org/t/cant-use-inner-classes-for-junit-categories/1500

Basically, the `OuterClass$InnerClass` notation does work, but the dot notation does not.

**Comment by juddgaddie** [comment]
Thanks!
